version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  auth-microservice:
    build:
      context: ./Backend/authMicroservice
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: >
      sh -c "npx prisma migrate deploy &&
             npm run start"

  frontend:
    build:
      context: ./frontend
    ports:
      - '80:80'
    depends_on:
      - auth-microservice

volumes:
  postgres_data:
